package com.temariflow.service;

import com.temariflow.dto.ErpDtos.*; import com.temariflow.entity.*; import com.temariflow.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import java.math.*; import java.time.*; import java.util.*;

@Service @RequiredArgsConstructor
public class FinanceLibraryCommunicationService {
  private final ErpLookup lookup; private final StudentProfileRepository students; private final TeacherProfileRepository teachers; private final UserRepository users; private final InvoiceRepository invoices; private final ExpenseRepository expenses; private final PayrollRecordRepository payroll; private final BookRepository books; private final BookBorrowRepository borrows; private final AnnouncementRepository announcements; private final MessageRepository messages; private final NotificationRepository notifications;
  public Invoice invoice(InvoiceRequest r) { return invoices.save(Invoice.builder().school(lookup.school()).student(students.findById(r.studentId()).orElseThrow()).invoiceNumber(r.invoiceNumber()).amount(r.amount()).paidAmount(BigDecimal.ZERO).dueDate(r.dueDate()).status(InvoiceStatus.UNPAID).build()); }
  public Expense expense(ExpenseRequest r) { return expenses.save(Expense.builder().school(lookup.school()).category(r.category()).amount(r.amount()).expenseDate(r.expenseDate()).note(r.note()).build()); }
  public PayrollRecord payroll(PayrollRequest r) { var deductions = r.deductions()==null?BigDecimal.ZERO:r.deductions(); return payroll.save(PayrollRecord.builder().school(lookup.school()).teacher(teachers.findById(r.teacherId()).orElseThrow()).payrollMonth(r.payrollMonth()).grossSalary(r.grossSalary()).deductions(deductions).netSalary(r.grossSalary().subtract(deductions)).paid(false).build()); }
  public Book book(BookRequest r) { return books.save(Book.builder().school(lookup.school()).title(r.title()).author(r.author()).isbn(r.isbn()).category(r.category()).totalCopies(r.totalCopies()).availableCopies(r.totalCopies()).status(r.totalCopies()>0?BookStatus.AVAILABLE:BookStatus.OUT_OF_STOCK).build()); }
  public BookBorrow borrow(BorrowRequest r) { var book = books.findById(r.bookId()).orElseThrow(); if (book.getAvailableCopies() <= 0) throw new IllegalStateException("Book out of stock"); book.setAvailableCopies(book.getAvailableCopies()-1); books.save(book); return borrows.save(BookBorrow.builder().school(lookup.school()).book(book).borrower(students.findById(r.studentId()).orElseThrow()).borrowedAt(LocalDate.now()).dueAt(r.dueAt()).fineAmount(BigDecimal.ZERO).status(BorrowStatus.BORROWED).build()); }
  public BookBorrow returnBook(UUID borrowId) { var b = borrows.findById(borrowId).orElseThrow(); b.setReturnedAt(LocalDate.now()); b.setStatus(BorrowStatus.RETURNED); var book = b.getBook(); book.setAvailableCopies(book.getAvailableCopies()+1); books.save(book); return borrows.save(b); }
  public Announcement announce(AnnouncementRequest r) { return announcements.save(Announcement.builder().school(lookup.school()).title(r.title()).body(r.body()).audienceRole(r.audienceRole()).build()); }
  public Message message(UUID senderId, MessageRequest r) { return messages.save(Message.builder().school(lookup.school()).sender(users.findById(senderId).orElseThrow()).recipient(users.findById(r.recipientId()).orElseThrow()).body(r.body()).status(MessageStatus.SENT).build()); }
  public Notification notify(UUID recipientId, String title, String body) { return notifications.save(Notification.builder().school(lookup.school()).recipient(users.findById(recipientId).orElseThrow()).title(title).body(body).read(false).build()); }
}
