/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTimetableRouteImport } from './routes/app.timetable'
import { Route as AppTicketsRouteImport } from './routes/app.tickets'
import { Route as AppTeachersRouteImport } from './routes/app.teachers'
import { Route as AppSubscriptionsRouteImport } from './routes/app.subscriptions'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppStudentResultsRouteImport } from './routes/app.student-results'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSectionDistributionRouteImport } from './routes/app.section-distribution'
import { Route as AppSchoolsRouteImport } from './routes/app.schools'
import { Route as AppSchoolProfileRouteImport } from './routes/app.school-profile'
import { Route as AppRevenueRouteImport } from './routes/app.revenue'
import { Route as AppReturnRouteImport } from './routes/app.return'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPayrollRouteImport } from './routes/app.payroll'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppMyClassesRouteImport } from './routes/app.my-classes'
import { Route as AppMyAttendanceRouteImport } from './routes/app.my-attendance'
import { Route as AppMarksEntryRouteImport } from './routes/app.marks-entry'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppGradesRouteImport } from './routes/app.grades'
import { Route as AppGlobalUsersRouteImport } from './routes/app.global-users'
import { Route as AppFinesRouteImport } from './routes/app.fines'
import { Route as AppFinanceReportsRouteImport } from './routes/app.finance-reports'
import { Route as AppFinanceOverviewRouteImport } from './routes/app.finance-overview'
import { Route as AppFilesRouteImport } from './routes/app.files'
import { Route as AppFeesStatusRouteImport } from './routes/app.fees-status'
import { Route as AppFeeCollectionRouteImport } from './routes/app.fee-collection'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppBorrowRouteImport } from './routes/app.borrow'
import { Route as AppBooksRouteImport } from './routes/app.books'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAttendanceOverviewRouteImport } from './routes/app.attendance-overview'
import { Route as AppAttendanceEntryRouteImport } from './routes/app.attendance-entry'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAnnouncementsFeedRouteImport } from './routes/app.announcements-feed'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'
import { Route as AppAddBookRouteImport } from './routes/app.add-book'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentResultsRoute = AppStudentResultsRouteImport.update({
  id: '/student-results',
  path: '/student-results',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSectionDistributionRoute = AppSectionDistributionRouteImport.update({
  id: '/section-distribution',
  path: '/section-distribution',
  getParentRoute: () => AppRoute,
} as any)
const AppSchoolsRoute = AppSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AppRoute,
} as any)
const AppSchoolProfileRoute = AppSchoolProfileRouteImport.update({
  id: '/school-profile',
  path: '/school-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueRoute = AppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnRoute = AppReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppMyClassesRoute = AppMyClassesRouteImport.update({
  id: '/my-classes',
  path: '/my-classes',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAttendanceRoute = AppMyAttendanceRouteImport.update({
  id: '/my-attendance',
  path: '/my-attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppMarksEntryRoute = AppMarksEntryRouteImport.update({
  id: '/marks-entry',
  path: '/marks-entry',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppGlobalUsersRoute = AppGlobalUsersRouteImport.update({
  id: '/global-users',
  path: '/global-users',
  getParentRoute: () => AppRoute,
} as any)
const AppFinesRoute = AppFinesRouteImport.update({
  id: '/fines',
  path: '/fines',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceReportsRoute = AppFinanceReportsRouteImport.update({
  id: '/finance-reports',
  path: '/finance-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceOverviewRoute = AppFinanceOverviewRouteImport.update({
  id: '/finance-overview',
  path: '/finance-overview',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesStatusRoute = AppFeesStatusRouteImport.update({
  id: '/fees-status',
  path: '/fees-status',
  getParentRoute: () => AppRoute,
} as any)
const AppFeeCollectionRoute = AppFeeCollectionRouteImport.update({
  id: '/fee-collection',
  path: '/fee-collection',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppBorrowRoute = AppBorrowRouteImport.update({
  id: '/borrow',
  path: '/borrow',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksRoute = AppBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceOverviewRoute = AppAttendanceOverviewRouteImport.update({
  id: '/attendance-overview',
  path: '/attendance-overview',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceEntryRoute = AppAttendanceEntryRouteImport.update({
  id: '/attendance-entry',
  path: '/attendance-entry',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsFeedRoute = AppAnnouncementsFeedRouteImport.update({
  id: '/announcements-feed',
  path: '/announcements-feed',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAddBookRoute = AppAddBookRouteImport.update({
  id: '/add-book',
  path: '/add-book',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/app/add-book': typeof AppAddBookRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/announcements-feed': typeof AppAnnouncementsFeedRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/attendance-entry': typeof AppAttendanceEntryRoute
  '/app/attendance-overview': typeof AppAttendanceOverviewRoute
  '/app/audit': typeof AppAuditRoute
  '/app/books': typeof AppBooksRoute
  '/app/borrow': typeof AppBorrowRoute
  '/app/classes': typeof AppClassesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/fee-collection': typeof AppFeeCollectionRoute
  '/app/fees-status': typeof AppFeesStatusRoute
  '/app/files': typeof AppFilesRoute
  '/app/finance-overview': typeof AppFinanceOverviewRoute
  '/app/finance-reports': typeof AppFinanceReportsRoute
  '/app/fines': typeof AppFinesRoute
  '/app/global-users': typeof AppGlobalUsersRoute
  '/app/grades': typeof AppGradesRoute
  '/app/health': typeof AppHealthRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/marks-entry': typeof AppMarksEntryRoute
  '/app/my-attendance': typeof AppMyAttendanceRoute
  '/app/my-classes': typeof AppMyClassesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/return': typeof AppReturnRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/school-profile': typeof AppSchoolProfileRoute
  '/app/schools': typeof AppSchoolsRoute
  '/app/section-distribution': typeof AppSectionDistributionRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/student-results': typeof AppStudentResultsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/app/add-book': typeof AppAddBookRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/announcements-feed': typeof AppAnnouncementsFeedRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/attendance-entry': typeof AppAttendanceEntryRoute
  '/app/attendance-overview': typeof AppAttendanceOverviewRoute
  '/app/audit': typeof AppAuditRoute
  '/app/books': typeof AppBooksRoute
  '/app/borrow': typeof AppBorrowRoute
  '/app/classes': typeof AppClassesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/fee-collection': typeof AppFeeCollectionRoute
  '/app/fees-status': typeof AppFeesStatusRoute
  '/app/files': typeof AppFilesRoute
  '/app/finance-overview': typeof AppFinanceOverviewRoute
  '/app/finance-reports': typeof AppFinanceReportsRoute
  '/app/fines': typeof AppFinesRoute
  '/app/global-users': typeof AppGlobalUsersRoute
  '/app/grades': typeof AppGradesRoute
  '/app/health': typeof AppHealthRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/marks-entry': typeof AppMarksEntryRoute
  '/app/my-attendance': typeof AppMyAttendanceRoute
  '/app/my-classes': typeof AppMyClassesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/return': typeof AppReturnRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/school-profile': typeof AppSchoolProfileRoute
  '/app/schools': typeof AppSchoolsRoute
  '/app/section-distribution': typeof AppSectionDistributionRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/student-results': typeof AppStudentResultsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/app/add-book': typeof AppAddBookRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/announcements-feed': typeof AppAnnouncementsFeedRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/attendance-entry': typeof AppAttendanceEntryRoute
  '/app/attendance-overview': typeof AppAttendanceOverviewRoute
  '/app/audit': typeof AppAuditRoute
  '/app/books': typeof AppBooksRoute
  '/app/borrow': typeof AppBorrowRoute
  '/app/classes': typeof AppClassesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/fee-collection': typeof AppFeeCollectionRoute
  '/app/fees-status': typeof AppFeesStatusRoute
  '/app/files': typeof AppFilesRoute
  '/app/finance-overview': typeof AppFinanceOverviewRoute
  '/app/finance-reports': typeof AppFinanceReportsRoute
  '/app/fines': typeof AppFinesRoute
  '/app/global-users': typeof AppGlobalUsersRoute
  '/app/grades': typeof AppGradesRoute
  '/app/health': typeof AppHealthRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/marks-entry': typeof AppMarksEntryRoute
  '/app/my-attendance': typeof AppMyAttendanceRoute
  '/app/my-classes': typeof AppMyClassesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/return': typeof AppReturnRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/school-profile': typeof AppSchoolProfileRoute
  '/app/schools': typeof AppSchoolsRoute
  '/app/section-distribution': typeof AppSectionDistributionRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/student-results': typeof AppStudentResultsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/verify-otp'
    | '/app/add-book'
    | '/app/announcements'
    | '/app/announcements-feed'
    | '/app/approvals'
    | '/app/attendance-entry'
    | '/app/attendance-overview'
    | '/app/audit'
    | '/app/books'
    | '/app/borrow'
    | '/app/classes'
    | '/app/expenses'
    | '/app/fee-collection'
    | '/app/fees-status'
    | '/app/files'
    | '/app/finance-overview'
    | '/app/finance-reports'
    | '/app/fines'
    | '/app/global-users'
    | '/app/grades'
    | '/app/health'
    | '/app/invoices'
    | '/app/marks-entry'
    | '/app/my-attendance'
    | '/app/my-classes'
    | '/app/payments'
    | '/app/payroll'
    | '/app/profile'
    | '/app/reports'
    | '/app/return'
    | '/app/revenue'
    | '/app/school-profile'
    | '/app/schools'
    | '/app/section-distribution'
    | '/app/settings'
    | '/app/student-results'
    | '/app/students'
    | '/app/subscriptions'
    | '/app/teachers'
    | '/app/tickets'
    | '/app/timetable'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/verify-otp'
    | '/app/add-book'
    | '/app/announcements'
    | '/app/announcements-feed'
    | '/app/approvals'
    | '/app/attendance-entry'
    | '/app/attendance-overview'
    | '/app/audit'
    | '/app/books'
    | '/app/borrow'
    | '/app/classes'
    | '/app/expenses'
    | '/app/fee-collection'
    | '/app/fees-status'
    | '/app/files'
    | '/app/finance-overview'
    | '/app/finance-reports'
    | '/app/fines'
    | '/app/global-users'
    | '/app/grades'
    | '/app/health'
    | '/app/invoices'
    | '/app/marks-entry'
    | '/app/my-attendance'
    | '/app/my-classes'
    | '/app/payments'
    | '/app/payroll'
    | '/app/profile'
    | '/app/reports'
    | '/app/return'
    | '/app/revenue'
    | '/app/school-profile'
    | '/app/schools'
    | '/app/section-distribution'
    | '/app/settings'
    | '/app/student-results'
    | '/app/students'
    | '/app/subscriptions'
    | '/app/teachers'
    | '/app/tickets'
    | '/app/timetable'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/verify-otp'
    | '/app/add-book'
    | '/app/announcements'
    | '/app/announcements-feed'
    | '/app/approvals'
    | '/app/attendance-entry'
    | '/app/attendance-overview'
    | '/app/audit'
    | '/app/books'
    | '/app/borrow'
    | '/app/classes'
    | '/app/expenses'
    | '/app/fee-collection'
    | '/app/fees-status'
    | '/app/files'
    | '/app/finance-overview'
    | '/app/finance-reports'
    | '/app/fines'
    | '/app/global-users'
    | '/app/grades'
    | '/app/health'
    | '/app/invoices'
    | '/app/marks-entry'
    | '/app/my-attendance'
    | '/app/my-classes'
    | '/app/payments'
    | '/app/payroll'
    | '/app/profile'
    | '/app/reports'
    | '/app/return'
    | '/app/revenue'
    | '/app/school-profile'
    | '/app/schools'
    | '/app/section-distribution'
    | '/app/settings'
    | '/app/student-results'
    | '/app/students'
    | '/app/subscriptions'
    | '/app/teachers'
    | '/app/tickets'
    | '/app/timetable'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timetable': {
      id: '/app/timetable'
      path: '/timetable'
      fullPath: '/app/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers': {
      id: '/app/teachers'
      path: '/teachers'
      fullPath: '/app/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions': {
      id: '/app/subscriptions'
      path: '/subscriptions'
      fullPath: '/app/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student-results': {
      id: '/app/student-results'
      path: '/student-results'
      fullPath: '/app/student-results'
      preLoaderRoute: typeof AppStudentResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/section-distribution': {
      id: '/app/section-distribution'
      path: '/section-distribution'
      fullPath: '/app/section-distribution'
      preLoaderRoute: typeof AppSectionDistributionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schools': {
      id: '/app/schools'
      path: '/schools'
      fullPath: '/app/schools'
      preLoaderRoute: typeof AppSchoolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/school-profile': {
      id: '/app/school-profile'
      path: '/school-profile'
      fullPath: '/app/school-profile'
      preLoaderRoute: typeof AppSchoolProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/revenue': {
      id: '/app/revenue'
      path: '/revenue'
      fullPath: '/app/revenue'
      preLoaderRoute: typeof AppRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/return': {
      id: '/app/return'
      path: '/return'
      fullPath: '/app/return'
      preLoaderRoute: typeof AppReturnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-classes': {
      id: '/app/my-classes'
      path: '/my-classes'
      fullPath: '/app/my-classes'
      preLoaderRoute: typeof AppMyClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-attendance': {
      id: '/app/my-attendance'
      path: '/my-attendance'
      fullPath: '/app/my-attendance'
      preLoaderRoute: typeof AppMyAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marks-entry': {
      id: '/app/marks-entry'
      path: '/marks-entry'
      fullPath: '/app/marks-entry'
      preLoaderRoute: typeof AppMarksEntryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grades': {
      id: '/app/grades'
      path: '/grades'
      fullPath: '/app/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/global-users': {
      id: '/app/global-users'
      path: '/global-users'
      fullPath: '/app/global-users'
      preLoaderRoute: typeof AppGlobalUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fines': {
      id: '/app/fines'
      path: '/fines'
      fullPath: '/app/fines'
      preLoaderRoute: typeof AppFinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance-reports': {
      id: '/app/finance-reports'
      path: '/finance-reports'
      fullPath: '/app/finance-reports'
      preLoaderRoute: typeof AppFinanceReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance-overview': {
      id: '/app/finance-overview'
      path: '/finance-overview'
      fullPath: '/app/finance-overview'
      preLoaderRoute: typeof AppFinanceOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees-status': {
      id: '/app/fees-status'
      path: '/fees-status'
      fullPath: '/app/fees-status'
      preLoaderRoute: typeof AppFeesStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fee-collection': {
      id: '/app/fee-collection'
      path: '/fee-collection'
      fullPath: '/app/fee-collection'
      preLoaderRoute: typeof AppFeeCollectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/borrow': {
      id: '/app/borrow'
      path: '/borrow'
      fullPath: '/app/borrow'
      preLoaderRoute: typeof AppBorrowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/books': {
      id: '/app/books'
      path: '/books'
      fullPath: '/app/books'
      preLoaderRoute: typeof AppBooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance-overview': {
      id: '/app/attendance-overview'
      path: '/attendance-overview'
      fullPath: '/app/attendance-overview'
      preLoaderRoute: typeof AppAttendanceOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance-entry': {
      id: '/app/attendance-entry'
      path: '/attendance-entry'
      fullPath: '/app/attendance-entry'
      preLoaderRoute: typeof AppAttendanceEntryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements-feed': {
      id: '/app/announcements-feed'
      path: '/announcements-feed'
      fullPath: '/app/announcements-feed'
      preLoaderRoute: typeof AppAnnouncementsFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/add-book': {
      id: '/app/add-book'
      path: '/add-book'
      fullPath: '/app/add-book'
      preLoaderRoute: typeof AppAddBookRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddBookRoute: typeof AppAddBookRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAnnouncementsFeedRoute: typeof AppAnnouncementsFeedRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAttendanceEntryRoute: typeof AppAttendanceEntryRoute
  AppAttendanceOverviewRoute: typeof AppAttendanceOverviewRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBooksRoute: typeof AppBooksRoute
  AppBorrowRoute: typeof AppBorrowRoute
  AppClassesRoute: typeof AppClassesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFeeCollectionRoute: typeof AppFeeCollectionRoute
  AppFeesStatusRoute: typeof AppFeesStatusRoute
  AppFilesRoute: typeof AppFilesRoute
  AppFinanceOverviewRoute: typeof AppFinanceOverviewRoute
  AppFinanceReportsRoute: typeof AppFinanceReportsRoute
  AppFinesRoute: typeof AppFinesRoute
  AppGlobalUsersRoute: typeof AppGlobalUsersRoute
  AppGradesRoute: typeof AppGradesRoute
  AppHealthRoute: typeof AppHealthRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppMarksEntryRoute: typeof AppMarksEntryRoute
  AppMyAttendanceRoute: typeof AppMyAttendanceRoute
  AppMyClassesRoute: typeof AppMyClassesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReturnRoute: typeof AppReturnRoute
  AppRevenueRoute: typeof AppRevenueRoute
  AppSchoolProfileRoute: typeof AppSchoolProfileRoute
  AppSchoolsRoute: typeof AppSchoolsRoute
  AppSectionDistributionRoute: typeof AppSectionDistributionRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentResultsRoute: typeof AppStudentResultsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddBookRoute: AppAddBookRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAnnouncementsFeedRoute: AppAnnouncementsFeedRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAttendanceEntryRoute: AppAttendanceEntryRoute,
  AppAttendanceOverviewRoute: AppAttendanceOverviewRoute,
  AppAuditRoute: AppAuditRoute,
  AppBooksRoute: AppBooksRoute,
  AppBorrowRoute: AppBorrowRoute,
  AppClassesRoute: AppClassesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFeeCollectionRoute: AppFeeCollectionRoute,
  AppFeesStatusRoute: AppFeesStatusRoute,
  AppFilesRoute: AppFilesRoute,
  AppFinanceOverviewRoute: AppFinanceOverviewRoute,
  AppFinanceReportsRoute: AppFinanceReportsRoute,
  AppFinesRoute: AppFinesRoute,
  AppGlobalUsersRoute: AppGlobalUsersRoute,
  AppGradesRoute: AppGradesRoute,
  AppHealthRoute: AppHealthRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppMarksEntryRoute: AppMarksEntryRoute,
  AppMyAttendanceRoute: AppMyAttendanceRoute,
  AppMyClassesRoute: AppMyClassesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppReturnRoute: AppReturnRoute,
  AppRevenueRoute: AppRevenueRoute,
  AppSchoolProfileRoute: AppSchoolProfileRoute,
  AppSchoolsRoute: AppSchoolsRoute,
  AppSectionDistributionRoute: AppSectionDistributionRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentResultsRoute: AppStudentResultsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
